#! /usr/bin/env python
# encoding: utf-8

from waflib import Context

VERSION = Context.g_module.VERSION

bld.stlib(
    features='cxx',
    source=bld.path.ant_glob('**/*.cpp'),
    target='gauge',
    export_defines=['STEINWURF_GAUGE_VERSION="{}"'.format(VERSION)],
    export_includes=['..'],
    use=['tables', 'boost_chrono', 'boost_system', 'boost_program_options'])
