all:
	g++ main.cpp -o benchmark --std=c++0x -I../../src -L../../build/linux -lgauge -L../../build/linux/__root__/home/mvp/dev/bundle_dependencies/boost-1.2.0/ -lboost_chrono -lboost_program_options -lboost_system -lrt
